version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
    # Forward host port 5433 to docker port 5432 just in case of local conflicts
      - "5433:5432"
    volumes:
      - ./src/main/resources/initdb:/docker-entrypoint-initdb.d